//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAkonBD.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [Key] //Anotacion de llave primario
        public int idUsuario { get; set; }
        public string nombreUsuario { get; set; }

        [Display(Name ="Nombre del Departamento")] //Anotacion para modular el nombre de la propiedad
        [MaxLength(30,ErrorMessage ="Este campo no puede ser superior a 30 caracteres")]
        public string departUsuario { get; set; }
    }
}
